-- ============================================================================
-- cinematic-animations.lua - Sprite-Sheet Animation Registry & Player
-- ============================================================================
-- PURPOSE: Provides a shared registry of looping sprite-sheet animations and
--          a reusable playback engine for cycling texture atlas frames via
--          SetTexCoord(). Used by both the player cinematic frame and the
--          master action-editor live preview.
--
-- RESPONSIBILITIES:
--   - Animation registry (key -> atlas metadata)
--   - Shared sprite-sheet playback logic (start / update / stop)
--   - TexCoord math for grid-based atlas frames
--
-- USAGE:
--   local anims = EreaRpLibraries:CinematicAnimations()
--   local state = anims.StartAnimation(texture, "candle_burn")
--   -- inside OnUpdate:
--   anims.UpdateAnimation(state, elapsed)
--   -- to stop:
--   anims.StopAnimation(state, texture)
-- ============================================================================

-- ============================================================================
-- ANIMATION REGISTRY
-- ============================================================================
-- Auto-generated by build.ps1 from blp-videos/*.blp files.
-- The global EreaRpAnimationRegistry is loaded from blp-videos/animation-registry.lua
-- which must appear before this file in the TOC load order.
-- ============================================================================

local ANIMATION_REGISTRY = EreaRpAnimationRegistry or {}
local _registeredExtensions = {}

-- ============================================================================
-- GetAnimation(key) - Look up animation metadata by key
-- ============================================================================
-- @param key: string animation key
-- @returns: animation table or nil
-- ============================================================================
local function GetAnimation(key)
    if not key or key == "" then return nil end
    local entry = ANIMATION_REGISTRY[key]
    if type(entry) == "table" and entry.cols then return entry end
    return nil
end

-- ============================================================================
-- GetAnimationList() - Return sorted list of {key, label} for dropdowns
-- ============================================================================
-- @returns: array of { key = "candle_burn", label = "candle_burn" }
-- ============================================================================
local function GetAnimationList()
    local list = {}
    for key, entry in pairs(ANIMATION_REGISTRY) do
        if type(entry) == "table" and entry.cols then
            local label = string.gsub(key, "_", " ")
            table.insert(list, { key = key, label = label })
        end
    end
    -- Sort alphabetically by key
    table.sort(list, function(a, b) return a.key < b.key end)
    return list
end

-- ============================================================================
-- SPRITE-SHEET PLAYBACK ENGINE
-- ============================================================================

-- ============================================================================
-- StartAnimation(texture, animKey) - Begin cycling a sprite-sheet animation
-- ============================================================================
-- @param texture: WoW Texture widget to animate
-- @param animKey: string key into ANIMATION_REGISTRY
-- @returns: state table (pass to UpdateAnimation), or nil if key not found
-- ============================================================================
local function StartAnimation(texture, animKey, loopMode)
    local anim = GetAnimation(animKey)
    if not anim then return nil end

    texture:SetTexture(anim.texture)
    texture:Show()

    -- Set initial frame (frame 0)
    local col = 0
    local row = 0
    texture:SetTexCoord(
        col / anim.cols, (col + 1) / anim.cols,
        row / anim.rows, (row + 1) / anim.rows
    )

    return {
        animKey = animKey,
        cols = anim.cols,
        rows = anim.rows,
        totalFrames = anim.totalFrames,
        fps = anim.fps,
        elapsed = 0,
        currentFrame = 0,
        direction = 1,  -- 1 = forward, -1 = backward (ping-pong only)
        loopMode = loopMode or "pingpong"  -- "pingpong" | "cycle"
    }
end

-- ============================================================================
-- UpdateAnimation(state, elapsed) - Advance animation by elapsed seconds
-- ============================================================================
-- Call this from OnUpdate. Uses ping-pong playback: cycles forward through
-- all frames, then backward, creating a smooth bounce loop that avoids the
-- jarring snap from last frame back to first.
--
-- For 16 frames: 0,1,2,...,14,15,14,13,...,1,0,1,2,...
--
-- @param state: state table from StartAnimation
-- @param elapsed: seconds since last frame (arg1 in OnUpdate)
-- @param texture: WoW Texture widget being animated
-- ============================================================================
local function UpdateAnimation(state, elapsed, texture)
    if not state or not texture then return end

    state.elapsed = state.elapsed + elapsed
    local frameDuration = 1 / state.fps
    if state.elapsed < frameDuration then return end

    -- Advance frame (may skip multiple if lag spike)
    while state.elapsed >= frameDuration do
        state.elapsed = state.elapsed - frameDuration

        if state.loopMode == "cycle" then
            -- Cycle: play forward, wrap from last frame back to first
            state.currentFrame = state.currentFrame + 1
            if state.currentFrame >= state.totalFrames then
                state.currentFrame = 0
            end
        else
            -- Ping-pong: play forward then backward, reversing at each boundary
            state.currentFrame = state.currentFrame + state.direction
            if state.currentFrame >= state.totalFrames - 1 then
                state.currentFrame = state.totalFrames - 1
                state.direction = -1
            elseif state.currentFrame <= 0 then
                state.currentFrame = 0
                state.direction = 1
            end
        end
    end

    -- Calculate grid position
    -- Lua 5.0: math.mod instead of %
    local col = math.mod(state.currentFrame, state.cols)
    local row = math.floor(state.currentFrame / state.cols)

    texture:SetTexCoord(
        col / state.cols, (col + 1) / state.cols,
        row / state.rows, (row + 1) / state.rows
    )
end

-- ============================================================================
-- StopAnimation(state, texture) - Stop animation and hide texture
-- ============================================================================
-- @param state: state table (will be cleared)
-- @param texture: WoW Texture widget to hide
-- ============================================================================
local function StopAnimation(state, texture)
    if texture then
        texture:Hide()
        texture:SetTexture("")
    end
    -- Caller should nil out their state reference
end

-- ============================================================================
-- RegisterExtension(registry, addonName) - Merge external animations into registry
-- ============================================================================
-- Called by extension addons at load time. Must be called before PLAYER_LOGIN.
-- addonName is recorded and reported in STATUS_RESPONSE so GMs can verify
-- all players have the extension loaded.
--
-- @param registry: table of { [key] = { texture, cols, rows, totalFrames, fps } }
-- @param addonName: string name of the extension addon (optional but recommended)
-- ============================================================================
local function RegisterExtension(registry, addonName)
    if not registry then return end
    for key, anim in pairs(registry) do
        ANIMATION_REGISTRY[key] = anim
    end
    if addonName and addonName ~= "" then
        table.insert(_registeredExtensions, addonName)
    end
end

-- ============================================================================
-- GetRegisteredExtensions() - Return list of registered extension addon names
-- ============================================================================
local function GetRegisteredExtensions()
    return _registeredExtensions
end

-- ============================================================================
-- EXPORT
-- ============================================================================

function EreaRpLibraries:CinematicAnimations()
    return {
        GetAnimation = GetAnimation,
        GetAnimationList = GetAnimationList,
        StartAnimation = StartAnimation,
        UpdateAnimation = UpdateAnimation,
        StopAnimation = StopAnimation,
        RegisterExtension = RegisterExtension,
        GetRegisteredExtensions = GetRegisteredExtensions,
        REGISTRY = ANIMATION_REGISTRY
    }
end
