-- Animation registry - auto-generated by build.ps1, do not edit manually
-- To add animations: place .blp files in this folder and rebuild
EreaRpAnimationRegistry = {
    alchemical_explosion = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Alchemical_explosion",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    boom_flag = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\BOOM_flag",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    campfire = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Campfire",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    candle_dying = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Candle_dying",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    confetti_cannon = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Confetti_cannon",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    fel_flame = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Fel_flame",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    fireworks_burst = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Fireworks_burst",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    flower_blooming = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Flower_blooming",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    fog_rolling = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Fog_rolling",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    ice_forming = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Ice_forming",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    leaf_vortex = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Leaf_vortex",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    lit_candle = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Lit_candle",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    moonstone_compass = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Moonstone_compass",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    pie_splat = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Pie_splat",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    sunfire_beacon = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Sunfire_beacon",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
    water_droplet = {
        texture = "Interface\\AddOns\\erea-rp-player\\blp-videos\\Water_droplet",
        cols = 4, rows = 4, totalFrames = 16, fps = 8
    },
}